FROM apache/airflow:2.7.1-python3.9@sha256:fadcd177ae17f604f587aa8761bbd398685e00d379a2da7eab1c4ca4cb476f49
USER root

# Install OpenJDK-11
RUN apt update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y ant && \
    apt-get install -y procps && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-arm64
RUN export JAVA_HOME

USER airflow

RUN pip install \
    lxml \
    pyspark==3.3.2 \
    apache-airflow-providers-apache-spark \
    requests \
    pandas

COPY --chown=airflow:root ./dags /opt/airflow/dags
