# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\"\x99\x01\n\x08\x45mployee\x12\x0e\n\x06\x65mp_id\x18\x01 \x01(\t\x12\x15\n\remployee_name\x18\x02 \x01(\t\x12\x12\n\ndepartment\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0e\n\x06salary\x18\x05 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x05\x12\r\n\x05\x62onus\x18\x07 \x01(\x05\x12\n\n\x02ts\x18\x08 \x01(\x03\x12\x0b\n\x03new\x18\t \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPLOYEE._serialized_start=19
  _EMPLOYEE._serialized_end=172
# @@protoc_insertion_point(module_scope)
